version: "3.8"

services:
  flask:
    container_name: flask
    restart: always
    image: thowbikdustan/distroless-flask
    expose:
      - "5000"
    environment:
      - FLASK_ENV=DEBUG

  nginx:
    container_name: nginx
    restart: always
    image: thowbikdustan/distroless-nginx
    ports:
      - "80:80"
    depends_on:
      - flask
