name: Application Build & Signing

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  Image_Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0
      
      - name: Image_Build
        run : |
          FLASK_IMAGE=distroless-flask
          NGINX_IMAGE=distroless-nginx
          docker build -t $DOCKER_USERNAME/$FLASK_IMAGE ./flask
          docker build -t $DOCKER_USERNAME/$NGINX_IMAGE ./nginx
          echo $DOCKER_PAT | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/$FLASK_IMAGE
          docker push $DOCKER_USERNAME/$NGINX_IMAGE
          echo -n $COSIGN_PASSWORD | cosign sign --key env://COSIGN_KEY -a "Author=root@thowbikdustan.me" $DOCKER_USERNAME/$FLASK_IMAGE
          echo -n $COSIGN_PASSWORD | cosign sign --key env://COSIGN_KEY -a "Author=root@thowbikdustan.me" $DOCKER_USERNAME/$NGINX_IMAGE
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
